version: '3.1'

services:
  api:
    build: .
    ports:
      - "5000:5000"
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
